services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7.0.14
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: