services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./api/:/home/node/app

  mongo:
    image: mongo:7.0.14
    ports:
      - "27017:27017"