services:
  api:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./api/:/home/node/app

  mongo:
    build:
      context: ./
      dockerfile: docker/mongo/Dockerfile
    ports:
      - "27017:27017"