services:
  api:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`f1-api.devprod.fr`)"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.tls.certresolver=myresolver"
    networks:
      - traefik_routing

  mongo:
    build:
      context: ./
      dockerfile: docker/mongo/Dockerfile
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - traefik_routing
volumes:
  mongo-data:

networks:
  traefik_routing:
    external: true