FROM node:20.17-slim AS builder
WORKDIR /home/node/app

COPY ./api/package*.json ./
RUN npm install --ignore-scripts

COPY ./api .


FROM node:20.17-slim AS development
WORKDIR /home/node/app
COPY --from=builder /home/node/app .

EXPOSE 3000

RUN useradd --user-group --create-home --shell /bin/false appuser
USER appuser


CMD ["npm", "run", "dev"]