FROM node:20.17-slim AS builder
WORKDIR /home/node/app

COPY ./api/package*.json ./
RUN npm ci --only=production --ignore-scripts

COPY ./api .


FROM node:20.17-slim AS production
WORKDIR /home/node/app
COPY --from=builder /home/node/app .

EXPOSE 3000

RUN useradd --user-group --create-home --shell /bin/false appuser
USER appuser

CMD ["node", "dist/server.js"]