FROM node:20.17-slim AS builder
WORKDIR /home/node/app

COPY ./api .
RUN npm ci --ignore-scripts

RUN npm run build

FROM node:20.17-slim AS production
WORKDIR /home/node/app
COPY --from=builder /home/node/app/dist .

ENV TZ=Europe/Paris

EXPOSE 3000

USER node

CMD ["node", "server.js"]